'use client';
import {sitePath} from "../lib/site-path";
import {demoFetch as fetch,resetDemo,switchDemoUser,demoUsers,demoFileUrl} from './demo-api';
import { useEffect,useRef,useState } from 'react';
import { LayoutDashboard,Wallet,Layers,UserRound,LogOut,Plus,ArrowUpRight,CheckCircle2,FileCheck,ShieldCheck,Bell,Download } from 'lucide-react';
type R={id:string;kind:string;status:string;ownerId:string;data:Record<string,any>;createdAt:string};
type Field={key:string;label:string;type?:string;options?:{value:string;label:string}[];value?:any;optional?:boolean;when?:[string,string]};
const names:Record<string,string>={research:'研发',sales:'销售',investor:'投资',manage:'DAO 管理',finance:'财务',review:'成果确认',active:'进行中',pending:'待审批',approved:'已通过',rejected:'已退回',confirmed:'已确认',draft:'草稿',published:'已发布',cancelled:'已取消',paid:'已支付',voting:'投票中',passed:'已通过',executed:'已执行',open:'待使用',used:'已使用',investment:'出资',revenue:'业务收入',product:'产品',project:'项目',budget:'预算',rule:'分账规则',permission:'权限授予',general:'一般提案'};
const money=(n:number=0)=>(n/100).toLocaleString('zh-CN',{style:'currency',currency:'CNY'});
const date=(s:string)=>new Date(s).toLocaleString('zh-CN');
export default function DaoDetail({initialDaoId,initialView='center',onBack,onChanged}:{initialDaoId:string;initialView?:string;onBack:()=>void;onChanged:()=>void}){
 const [state,S]=useState<any>(null),[loading,L]=useState(true),[error,E]=useState(''),[busy,B]=useState(false),[view,V]=useState(initialView),[tab,T]=useState('overview'),[role,Role]=useState('research'),[daoId,D]=useState(initialDaoId);
 const [auth,A]=useState('login'),[setup,Setup]=useState(false),[notice,N]=useState(''),[modal,M]=useState<{title:string;op:string;fields:Field[];fixed?:any;requestId:string}|null>(null);
 const [formChoice,Choice]=useState<Record<string,string>>({});
 const dialog=useRef<HTMLDialogElement>(null);
 async function api(url:string,data?:any){const response=await fetch(url,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const result=await response.json();if(!response.ok){const error=Object.assign(new Error(result.error??'请求失败'),{status:response.status});throw error;}return result;}
 async function refresh(id=daoId){try{const next=await api('/api/state'+(id?'?dao='+id:''));S(next);D(next.dao?.id??'');Role(r=>next.member?.roles.includes(r)?r:next.member?.roles[0]??'research');}catch(e){if((e as any).status===401){S(null);try{const b=await api('/api/bootstrap');Setup(b.needsSetup);A(b.needsSetup?'setup':new URLSearchParams(location.search).has('invite')?'register':'login');}catch{E('本地服务不可用，请确认数据库已启动后刷新页面。');}}else E((e as Error).message||'无法连接本地服务，请刷新后重试');}finally{L(false);}}
 useEffect(()=>{refresh();},[]);
 useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close();},[modal]);
 const records:R[]=state?.records??[],members:any[]=state?.members??[],me=state?.user?.id;
 const can=(p:string)=>state?.member?.permissions.includes(p);
 const list=(kind:string)=>records.filter(r=>r.kind===kind);
 const target=(id:string)=>records.find(r=>r.id===id)?.data.name??'DAO';
 const person=(id:string)=>members.find(m=>m.userId===id)?.user.name??'成员';
 const opts=(items:R[])=>items.map(r=>({value:r.id,label:r.data.name??r.data.title??r.data.note??r.id.slice(0,8)}));
 const people=members.filter(m=>m.status==='active').map(m=>({value:m.userId,label:m.user.name+' · '+m.user.opc}));
 const field=(key:string,label:string,type='text',options?:Field['options'],value?:any):Field=>({key,label,type,options,value});
 function open(title:string,op:string,fields:Field[],fixed:any={}){E('');Choice(Object.fromEntries(fields.filter(f=>f.type==='select').map(f=>[f.key,f.value??''])));M({title,op,fields,fixed,requestId:crypto.randomUUID()});}
 async function act(op:string,input:any,requestId=crypto.randomUUID()){B(true);E('');try{const result=await api('/api/action',{daoId,op,input,requestId});await refresh();onChanged();N('操作已保存');return result;}catch(e){E((e as Error).message);throw e;}finally{B(false);}}
 async function quick(op:string,input:any){try{await act(op,input);}catch{}}
 function review(op:string,id:string,approve:boolean){open(approve?'确认通过':'退回并说明原因',op,[field('note','审批说明')],{id,approve});}
 function entity(kind:string,r?:R){open(r?'编辑'+names[kind]:'创建'+names[kind],r?'entity.update':'entity.create',[field('name','名称','text',undefined,r?.data.name),field('description','目标与说明','textarea',undefined,r?.data.description),field('leaderId','负责人','select',people,r?.data.leaderId??me),field('progress','进度（0–100）','number',undefined,r?.data.progress??0),{...field('links','关联的'+(kind==='product'?'项目':'产品'),'multi',opts(list(kind==='product'?'project':'product')),r?.data.links??[]),optional:true}],{kind,id:r?.id});}
 function evidence(r?:R){const own=list('participation').filter(p=>p.ownerId===me&&p.status==='approved').map(p=>p.data.targetId);const available=records.filter(r=>['product','project'].includes(r.kind)&&(state?.user?.isPlatformAdmin||own.includes(r.id)||r.data.leaderId===me));open('提交成果','evidence.submit',[field('targetId','归属对象','select',opts(available),r?.data.targetId),field('title','成果名称','text',undefined,r?.data.title),field('description','贡献说明','textarea',undefined,r?.data.description),{...field('fileId','成果附件（最大 10MB）','file'),optional:true}],{id:r?.id,fileId:r?.data.fileId});}
 function proposal(){open('发起提案','proposal.create',[field('type','提案类型','select',['general','budget','rule','permission'].map(value=>({value,label:names[value]})),'general'),field('title','提案标题'),field('description','内容、金额、用途及执行条件','textarea'),field('deadline','投票截止时间','datetime-local'),{...field('budgetAmount','批准上限（元）','number'),when:['type','budget']},{...field('targetUserId','授予成员','select',people),when:['type','permission']},{...field('permission','权限','select',['manage','finance','review'].map(value=>({value,label:names[value]}))),when:['type','permission']},{...field('shares','成员比例（总计 100%）','shares'),when:['type','rule']}]);}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!modal)return;B(true);E('');try{const form=e.currentTarget,fd=new FormData(form),input:any={...modal.fixed};for(const f of modal.fields.filter(f=>!f.when||formChoice[f.when[0]]===f.when[1])){if(f.type==='multi')input[f.key]=fd.getAll(f.key);else if(f.type==='shares'){input.shares=people.map(p=>({userId:p.value,bps:Math.round(Number(fd.get('share-'+p.value)??0)*100)})).filter(p=>p.bps>0);}else if(f.type==='file'){const file=fd.get(f.key);if(file instanceof File&&file.size){const upload=new FormData();upload.set('file',file);upload.set('daoId',daoId);const res=await fetch('/api/upload',{method:'POST',body:upload});const data=await res.json();if(!res.ok)throw new Error(data.error);input[f.key]=data.id;}}else input[f.key]=fd.get(f.key);}
 const submitter=(e.nativeEvent as SubmitEvent).submitter as HTMLButtonElement;const op=submitter?.value==='draft'?'evidence.save':modal.op;const result=await act(op,input,modal.requestId);if(op==='invite')N('已创建一位虚拟待加入成员，可在成员列表审批。不会发送真实邀请。');M(null);}catch(e){E((e as Error).message);}finally{B(false);}}
 async function acceptInvite(){B(true);E('');try{await api('/api/join',{token:new URLSearchParams(location.search).get('invite')});history.replaceState(null,'',sitePath('/'));await refresh();N('加入申请已提交，请等待管理员审批');}catch(e){E((e as Error).message);}finally{B(false);}}
 async function signIn(e:React.FormEvent<HTMLFormElement>){e.preventDefault();B(true);E('');const data=Object.fromEntries(new FormData(e.currentTarget));try{await api('/api/'+auth,{...data,token:new URLSearchParams(location.search).get('invite')});if(auth==='register')history.replaceState(null,'',sitePath('/'));await refresh();}catch(e){E((e as Error).message);}finally{B(false);}}
 const earned=list('allocation').filter(r=>r.status==='published').flatMap(r=>r.data.rows).filter((r:any)=>r.userId===me).reduce((n:number,r:any)=>n+r.amount,0);
 const reserved=list('withdrawal').filter(r=>r.ownerId===me&&['pending','approved','paid'].includes(r.status)).reduce((n,r)=>n+r.data.amount,0);
 const income=list('income').reduce((n,r)=>n+r.data.amount,0),expense=list('expense').reduce((n,r)=>n+r.data.amount,0),paid=state?.treasury?.paid??0;
 const allocated=list('allocation').filter(r=>r.status!=='cancelled').reduce((n,r)=>n+r.data.amount,0);
 const assets=records.filter(r=>['product','project'].includes(r.kind));
 function attachment(id:string){const f=records.find(r=>r.id===id&&r.kind==='file');return f?<a className="file" href={demoFileUrl(id)} download="演示附件说明.txt"><Download size={14}/>{f.data.name}<small title={f.data.sha256}>演示摘要 {f.data.sha256.slice(0,12)}…</small></a>:null;}
 const empty=(message:string)=><div className="empty"><Layers size={28}/><p>{message}</p></div>;
 function cards(items:R[],render:(r:R)=>React.ReactNode){return items.length?items.map(r=><article className="card" key={r.id}>{render(r)}</article>):empty('暂无记录，新增操作后会保存在这里。');}
 const status=(r:R)=><span className={'badge '+r.status}>{names[r.status]??r.status}</span>;
 if(loading)return <main className="auth"><p>正在连接本地数据库…</p></main>;
 if(!state)return <main className="auth"><form onSubmit={signIn} className="auth-card"><img src={sitePath("/logo.png")} width="64" height="64" alt="PonyDAO"/><p className="eyebrow">PONYDAO / LOCAL MVP</p><h1>{auth==='setup'?'创建你的 DAO':auth==='register'?'接受 DAO 邀请':'欢迎回来'}</h1><p className="muted">{auth==='setup'?'首次启动：创建创始成员账户与 PONYGOGO DAO。':'登录后继续协作、治理与收益分配。'}</p>{auth!=='login'&&<><label>姓名<input name="name" required maxLength={100}/></label><label>OPC 名称<input name="opc" required maxLength={100}/></label></>}<label>邮箱<input name="email" type="email" required autoComplete="username"/></label><label>密码（至少 10 位）<input name="password" type="password" minLength={10} maxLength={128} autoComplete={auth==='login'?'current-password':'new-password'} required/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'正在处理…':auth==='setup'?'初始化平台':auth==='register'?'注册并申请加入':'登录'}</button>{!setup&&<button type="button" className="link" onClick={()=>A(auth==='login'?'register':'login')}>{auth==='login'?'使用邀请链接注册':'已有账户，返回登录'}</button>}</form></main>;
 if(!state.dao)return <main className="auth"><div className="auth-card"><h1>成员申请已提交</h1><p>请等待 DAO 管理员批准加入。</p>{error&&<p className="error">{error}</p>}{new URLSearchParams(location.search).has('invite')&&<button disabled={busy} onClick={acceptInvite}>接受当前邀请</button>}<button onClick={()=>refresh()}>刷新状态</button><button onClick={async()=>{await api('/api/logout',{});await refresh();}}>退出登录</button></div></main>;
 return <div className="dao-detail"> <main className="main"><div className="detail-back"><button onClick={onBack}>← 返回 DAO 中心</button><span>DAO 中心 / {state.dao.name}</span></div><div className="tabs detail-nav">{[['center','DAO 详情'],['work','协作与成果'],['ledger','DAO 金库与分账']].map(([key,label])=><button key={key} aria-pressed={view===key} className={view===key?'selected':''} onClick={()=>{V(key);T('overview');}}>{label}</button>)}</div><header><span>{state.dao.name} <b>/</b> {({work:'协作与成果',ledger:'DAO 金库与分账',center:state.dao.name,profile:'个人中心'} as any)[view]}</span><div><select aria-label="当前经济身份" value={role} onChange={e=>Role(e.target.value)}>{state.member.roles.map((r:string)=><option key={r} value={r}>{names[r]} OPC</option>)}</select></div></header><div className="content">
 {new URLSearchParams(location.search).has('invite')&&<div className="notice"><span>检测到 DAO 邀请，使用当前账户申请加入。</span><button disabled={busy} onClick={acceptInvite}>接受邀请</button></div>}{notice&&<div className="notice" role="status"><CheckCircle2 size={18}/><span>{notice}</span><button aria-label="关闭通知" onClick={()=>N('')}>×</button></div>}{error&&!modal&&<p className="error" role="alert">{error}</p>}
 <section className="heading"><div><p className="eyebrow">{view==='work'?'MY DAO WORKBENCH':view==='ledger'?'REVENUE & TREASURY':view==='center'?'DAO CENTER':'PROFILE & IDENTITY'}</p><h1>{({work:'协作与成果',ledger:'DAO 金库与分账',center:state.dao.name,profile:'个人中心'} as any)[view]}</h1><p className="muted">{view==='work'?`${state.user.name}，从今天的协作和待办开始。`:view==='ledger'?'每一笔收益，都有清晰的来源和分配依据。':view==='center'?'共同建设产品，推进项目，决定 DAO 的下一步。':'管理你的 OPC 身份与成员权限。'}</p></div>{view==='work'&&role!=='investor'&&<button className="primary" onClick={()=>evidence()}><Plus size={17}/>提交成果</button>}</section>
 {view==='work'&&<><div className="hero"><div><p>当前参与</p><h2>{state.dao.name} DAO</h2><span>{state.dao.mission}</span></div><button onClick={()=>{V('center');T('overview');}}>进入 DAO <ArrowUpRight size={17}/></button></div><div className="metrics"><article><small>我的可提现收益</small><strong>{money(earned-reserved)}</strong></article><article><small>{role==='investor'?'我的累计出资':'我参与的对象'}</small><strong>{role==='investor'?money(list('income').filter(r=>r.data.investorId===me).reduce((n,r)=>n+r.data.amount,0)):list('participation').filter(r=>r.ownerId===me&&r.status==='approved').length}</strong></article><article><small>待投票提案</small><strong>{list('proposal').filter(r=>r.status==='voting').length}</strong></article></div><div className="two"><section><h2><Bell size={19}/>我的待办</h2>{cards(list('notification').filter(r=>r.status==='unread'),r=><><p>{r.data.message}</p><button onClick={()=>quick('notification.read',{id:r.id})}>标为已读</button></>)}{can('manage')&&members.filter(m=>m.status==='pending').map(m=><article className="card" key={m.id}><h3>{m.user.name} 申请加入 DAO</h3><p>{m.user.opc}</p><button onClick={()=>quick('member.approve',{id:m.id,approve:true})}>批准加入</button><button onClick={()=>quick('member.approve',{id:m.id,approve:false})}>拒绝</button></article>)}</section><section><h2><FileCheck size={19}/>参与申请</h2>{cards(list('participation').filter(r=>r.ownerId===me||can('manage')||records.find(a=>a.id===r.data.targetId)?.data.leaderId===me),r=><><div className="row"><h3>{target(r.data.targetId)}</h3>{status(r)}</div><p>{person(r.ownerId)} · {names[r.data.role]} OPC</p><p>{r.data.note}</p>{r.status==='pending'&&(can('manage')||records.find(a=>a.id===r.data.targetId)?.data.leaderId===me)&&<div className="actions"><button onClick={()=>review('participation.review',r.id,true)}>批准</button><button onClick={()=>review('participation.review',r.id,false)}>退回</button></div>}</>)}</section></div><h2>成果与存证</h2>{cards(list('evidence'),r=><><div className="row"><h3>{r.data.title}</h3>{status(r)}</div><p>{target(r.data.targetId)} · {person(r.ownerId)} · 第 {r.data.version} 版</p><p>{r.data.description}</p>{r.data.fileId&&attachment(r.data.fileId)}{r.data.reviewNote&&<p>确认意见：{r.data.reviewNote}</p>}<div className="actions">{r.ownerId===me&&['draft','rejected'].includes(r.status)&&<button onClick={()=>evidence(r)}>编辑并重新提交</button>}{r.status==='pending'&&r.ownerId!==me&&(can('review')||assets.find(a=>a.id===r.data.targetId)?.data.leaderId===me)&&<><button onClick={()=>review('evidence.review',r.id,true)}>确认成果</button><button onClick={()=>review('evidence.review',r.id,false)}>退回</button></>}</div></>)}</>}
 {view==='center'&&<><div className="tabs">{[['overview','概览'],['product','产品'],['project','项目'],['members','成员'],['governance','治理提案']].map(([key,label])=><button aria-pressed={tab===key} className={tab===key?'selected':''} key={key} onClick={()=>T(key)}>{label}</button>)}</div>{tab==='overview'&&<><div className="hero"><div><small>共同治理 · 共同建设</small><h2>{state.dao.name}</h2><p>{state.dao.mission}</p></div><ShieldCheck size={48}/></div><div className="metrics"><article><small>成员</small><strong>{members.filter(m=>m.status==='active'&&m.id!=='platform-admin').length}</strong></article><article><small>产品</small><strong>{list('product').length}</strong></article><article><small>项目</small><strong>{list('project').length}</strong></article></div><article className="card"><h2>成员共同决定，贡献清晰分配</h2><p>投资 OPC 为 DAO 出资，研发与销售 OPC 参与产品或项目。预算、分账规则和权限授予通过提案决定。</p><p>投票采用一成员一票，超过提案发起时成员总数的一半赞成即通过；投票截止或全员投票后结算。</p></article>{can('manage')&&<button onClick={()=>open('创建 DAO','dao.create',[field('name','DAO 名称'),field('mission','使命与说明','textarea')])}>创建另一个 DAO</button>}</>}
 {['product','project'].includes(tab)&&<><div className="section-head"><h2>{names[tab]}列表</h2>{can('manage')&&<button className="primary" onClick={()=>entity(tab)}><Plus size={16}/>创建{names[tab]}</button>}</div><div className="two">{cards(list(tab),r=><><div className="row"><span className="badge">{names[r.kind]}</span><small>{r.data.progress}%</small></div><h2>{r.data.name}</h2><p>{r.data.description}</p><p>负责人：{person(r.data.leaderId)}</p><progress value={r.data.progress} max={100}/><p>关联：{(r.data.links??[]).map(target).join('、')||'暂无关联'}</p><div className="actions">{role!=='investor'&&<button onClick={()=>open('申请参与'+names[r.kind],'participate',[field('note','参与说明','textarea')],{targetId:r.id,role})}>申请参与</button>}{(r.data.leaderId===me||can('manage'))&&<button onClick={()=>open('更新进度','progress',[field('progress','进度（0–100）','number',undefined,r.data.progress),field('note','进度说明','textarea')],{id:r.id})}>更新进度</button>}{can('manage')&&<button onClick={()=>entity(r.kind,r)}>编辑</button>}</div></>)}</div></>}
 {tab==='members'&&<><div className="section-head"><h2>DAO 成员</h2>{can('manage')&&<button className="primary" onClick={()=>open('邀请 OPC 成员','invite',[field('email','成员邮箱','email'),field('roles','经济身份','multi',['research','sales','investor'].map(value=>({value,label:names[value]})))])}>邀请成员</button>}</div>{members.map(m=><article className="card" key={m.id}><div className="row"><h3>{m.user.name} · {m.user.opc}</h3><span className="badge">{m.status==='active'?'有效成员':names[m.status]}</span></div><p>{m.roles.map((r:string)=>names[r]+' OPC').join(' / ')}</p><small>权限：{m.permissions.map((p:string)=>names[p]).join('、')||'普通成员'}</small>{m.status==='pending'&&can('manage')&&<div className="actions"><button onClick={()=>quick('member.approve',{id:m.id,approve:true})}>批准加入</button><button onClick={()=>quick('member.approve',{id:m.id,approve:false})}>拒绝</button></div>}</article>)}</>}
 {tab==='governance'&&<><div className="section-head"><h2>提案与执行</h2><button className="primary" onClick={proposal}>发起提案</button></div>{cards(list('proposal'),r=><><div className="row"><small>{names[r.data.type]} · {person(r.ownerId)}</small>{status(r)}</div><h2>{r.data.title}</h2><p className="pre">{r.data.description}</p><p>截止：{date(new Date(r.data.deadline).toISOString())} · {list('vote').filter(v=>v.data.proposalId===r.id&&v.data.approve).length} 赞成 / {r.data.voters.length} 位成员</p>{r.data.budgetAmount&&<p>预算上限：{money(r.data.budgetAmount)}</p>}{r.data.shares&&<p>分账比例：{r.data.shares.map((s:any)=>person(s.userId)+' '+s.bps/100+'%').join('、')}</p>}{r.data.permission&&<p>授予 {person(r.data.targetUserId)}：{names[r.data.permission]}</p>}{r.data.executionNote&&<p>执行记录：{r.data.executionNote}</p>}<div className="actions">{r.status==='voting'&&<><button disabled={busy||!r.data.voters.includes(me)||list('vote').some(v=>v.data.proposalId===r.id&&v.ownerId===me)} onClick={()=>quick('vote',{id:r.id,approve:true})}>赞成</button><button disabled={busy||!r.data.voters.includes(me)||list('vote').some(v=>v.data.proposalId===r.id&&v.ownerId===me)} onClick={()=>quick('vote',{id:r.id,approve:false})}>反对</button><button onClick={()=>quick('proposal.close',{id:r.id})}>结算投票</button></>}{r.status==='passed'&&can('manage')&&<button onClick={()=>open('执行提案','proposal.execute',[field('note','执行说明','textarea')],{id:r.id})}>执行提案</button>}</div></>)}</>}
 </>}
 {view==='ledger'&&<><div className="hero"><div><small>我的可提现余额</small><h2>{money(earned-reserved)}</h2><p>累计已分配 {money(earned)} · 已提现或冻结 {money(reserved)}</p></div><button onClick={()=>open('申请提现','withdraw',[field('amount','金额（元）','number'),field('account','收款账户、开户行与户名','textarea')])}>申请提现 <ArrowUpRight size={17}/></button></div><div className="tabs">{[['overview','我的收益'],['treasury','DAO 金库'],['allocation','分账单'],['withdrawal','提现记录']].map(([key,label])=><button key={key} className={tab===key?'selected':''} onClick={()=>T(key)}>{label}</button>)}</div>
 {tab==='overview'&&cards(list('allocation').filter(r=>r.status==='published'&&r.data.rows.some((s:any)=>s.userId===me)),r=><><h3>{r.data.note}</h3><strong className="amount">{money(r.data.rows.find((s:any)=>s.userId===me).amount)}</strong><p>来源：{records.find(s=>s.id===r.data.sourceId)?.data.note} · 规则版本 {r.data.ruleVersion}</p><p>审核发布人：{person(r.data.reviewerId)} · {date(r.createdAt)}</p></>)}
 {tab==='treasury'&&<><div className="metrics"><article><small>累计收款</small><strong>{money(income)}</strong></article><article><small>运营支出</small><strong>{money(expense)}</strong></article><article><small>账面余额</small><strong>{money(income-expense-paid)}</strong></article></div><p className="muted">可用未分配资金 {money(income-expense-allocated)} · 已预留分账 {money(allocated)}。出资和业务收入按来源记录，预算支出及分账预留从来源扣减。已发布收益保留在金库账内，实际提现付款时才减少账面余额。</p>{can('finance')&&<div className="actions"><button className="primary" onClick={()=>open('确认收款','income',[field('category','收款类别','select',[{value:'revenue',label:'业务收入'},{value:'investment',label:'DAO 出资'}]),field('amount','到账金额（元）','number'),field('note','收款说明'),{...field('targetId','归属对象','select',opts(assets)),when:['category','revenue']},{...field('investorId','投资 OPC','select',people.filter(p=>members.find(m=>m.userId===p.value)?.roles.includes('investor'))),when:['category','investment']},field('fileId','收款凭证','file')])}>登记收款</button><button onClick={()=>open('登记预算支出','expense',[field('sourceId','资金来源','select',opts(list('income'))),field('proposalId','已执行预算提案','select',opts(list('proposal').filter(r=>r.status==='executed'&&r.data.type==='budget'))),field('amount','付款金额（元）','number'),field('note','支出说明'),field('fileId','付款凭证','file')])}>登记支出</button></div>}{cards([...list('income'),...list('expense')],r=><><div className="row"><h3>{r.data.note}</h3><strong>{r.kind==='expense'?'-':'+'}{money(r.data.amount)}</strong></div><p>{r.kind==='expense'?'预算支出':names[r.data.category]} · {r.data.investorId?person(r.data.investorId):target(r.data.targetId)} · {date(r.createdAt)}</p>{attachment(r.data.fileId)}</>)}</>}
 {tab==='allocation'&&<>{can('finance')&&<button className="primary" onClick={()=>open('生成分账草稿','allocation.create',[field('sourceId','业务收入来源','select',opts(list('income').filter(r=>r.data.category==='revenue'))),field('ruleId','已执行的分账规则','select',opts(list('proposal').filter(r=>r.status==='executed'&&r.data.type==='rule'))),field('amount','本次可分配金额（元）','number'),field('note','分账说明')])}>生成分账草稿</button>}{cards(list('allocation'),r=><><div className="row"><h3>{r.data.note}</h3>{status(r)}</div><p>总金额 {money(r.data.amount)} · 规则版本 {r.data.ruleVersion}</p>{r.data.rows.map((s:any)=><p key={s.userId}>{person(s.userId)} · {s.bps/100}% · {money(s.amount)}</p>)}{r.status==='draft'&&can('finance')&&<div className="actions"><button disabled={r.ownerId===me||busy} onClick={()=>quick('allocation.publish',{id:r.id})}>审核并发布</button><button onClick={()=>quick('allocation.cancel',{id:r.id})}>取消草稿</button>{r.ownerId===me&&<small>等待另一位财务成员审核</small>}</div>}</>)}</>}
 {tab==='withdrawal'&&cards(list('withdrawal'),r=><><div className="row"><h3>{money(r.data.amount)} · {person(r.ownerId)}</h3>{status(r)}</div><p>{r.data.account}</p><small>{date(r.createdAt)}</small>{r.data.fileId&&attachment(r.data.fileId)}{can('finance')&&r.ownerId!==me&&<div className="actions">{r.status==='pending'&&<><button onClick={()=>review('withdraw.review',r.id,true)}>审批通过</button><button onClick={()=>review('withdraw.review',r.id,false)}>驳回并释放余额</button></>}{r.status==='approved'&&<button onClick={()=>open('登记实际付款','withdraw.pay',[field('note','付款说明'),field('fileId','付款凭证','file')],{id:r.id})}>登记付款完成</button>}</div>}</>)}
 </>}
 {view==='profile'&&<><div className="two"><article className="card"><span className="avatar large">{state.user.name.slice(0,1)}</span><h2>{state.user.name}</h2><p>{state.user.opc}</p><p>{state.user.email}</p><button onClick={()=>open('编辑资料','profile',[field('name','姓名','text',undefined,state.user.name),field('opc','OPC 名称','text',undefined,state.user.opc)])}>编辑个人资料</button></article><article className="card"><h2>经济身份与 DAO 权限</h2><p>我的身份：{state.member.roles.map((r:string)=>names[r]+' OPC').join('、')}</p><p>我的权限：{state.member.permissions.map((r:string)=>names[r]).join('、')||'普通成员'}</p><p className="muted">身份用于组织工作视角，管理权限须通过 DAO 提案授予。</p></article></div><button onClick={async()=>{await api('/api/logout',{});await refresh();}}><LogOut size={16}/>退出登录</button><h2>DAO 操作记录</h2>{cards(list('audit').slice(0,30),r=><div className="row"><span>{person(r.ownerId)} · {r.data.op}</span><small>{date(r.createdAt)}</small></div>)}</>}
 </div></main>
 <dialog aria-labelledby="modal-title" ref={dialog} onCancel={()=>M(null)} onClick={e=>{if(e.target===dialog.current)M(null);}}><form onSubmit={submit}><div className="row"><h2 id="modal-title">{modal?.title}</h2><button type="button" aria-label="关闭" onClick={()=>M(null)}>×</button></div>{modal?.fields.filter(f=>!f.when||formChoice[f.when[0]]===f.when[1]).map(f=><label key={f.key}>{f.label}{f.optional?'（可选）':' *'}{f.type==='textarea'?<textarea name={f.key} required={!f.optional} defaultValue={f.value} rows={3}/>:f.type==='select'?<select name={f.key} onChange={e=>Choice(c=>({...c,[f.key]:e.target.value}))} required={!f.optional} defaultValue={f.value??''}><option value="">请选择</option>{f.options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='multi'?<div className="checks">{f.options?.map(o=><label key={o.value}><input type="checkbox" name={f.key} value={o.value} defaultChecked={f.value?.includes(o.value)}/>{o.label}</label>)}</div>:f.type==='shares'?<div className="shares">{people.map(p=><label key={p.value}><span>{p.label}</span><input name={'share-'+p.value} type="number" min="0" max="100" step="0.01" defaultValue="0"/>%</label>)}</div>:<input type={f.type??'text'} name={f.key} required={!f.optional} defaultValue={f.value} step={f.type==='number'?'0.01':undefined} min={f.type==='number'?'0':undefined}/>}</label>)}{error&&<p className="error" role="alert">{error}</p>}<div className="actions"><button className="primary" disabled={busy}>{busy?'正在保存…':'确认保存'}</button>{modal?.op==='evidence.submit'&&<button type="submit" value="draft" disabled={busy}>保存草稿</button>}<button type="button" disabled={busy} onClick={()=>M(null)}>取消</button></div></form></dialog>
 </div>;
}
