'use client';
import {sitePath} from "../lib/site-path";
import {demoFetch as fetch,resetDemo,switchDemoUser,demoUsers,demoFileUrl} from './demo-api';
import {useEffect,useRef,useState} from 'react';
import {LayoutDashboard,Wallet,Layers,UserRound,LogOut,ArrowUpRight,Search,Plus,ShieldCheck,ChevronRight} from 'lucide-react';
import DaoDetail from './DaoDetail';
const money=(n=0)=>(n/100).toLocaleString('zh-CN',{style:'currency',currency:'CNY'});
const labels:Record<string,string>={research:'研发',sales:'销售',investor:'投资',manage:'DAO 管理',finance:'财务',review:'成果确认',pending:'待审批',active:'已加入',approved:'已通过',rejected:'已退回',paid:'已支付',confirmed:'已确认',draft:'草稿',voting:'投票中'};
const navs=[['work','工作台',LayoutDashboard],['ledger','分账台',Wallet],['center','DAO 中心',Layers],['profile','个人中心',UserRound]] as const;
async function api(url:string,data?:any){
 const response=await fetch(url,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
 const body=await response.json();if(!response.ok)throw Object.assign(new Error(body.error??'操作失败'),{status:response.status});return body;
}
export default function App(){
 const [data,S]=useState<any>(null),[loading,L]=useState(true),[error,E]=useState(''),[busy,B]=useState(false);
 const [view,V]=useState('center'),[selected,D]=useState(''),[section,Section]=useState('center');
 const [search,SearchText]=useState(''),[filter,Filter]=useState('all'),[auth,Auth]=useState('login'),[invite,Invite]=useState('');
 const [modal,M]=useState<'dao'|'profile'|null>(null),[notice,N]=useState('');
 const dialog=useRef<HTMLDialogElement>(null);
 function readRoute(){const p=new URLSearchParams(location.search);D(p.get('dao')??'');V(p.get('dao')?'center':p.get('view')??'center');Section(p.get('section')??'center');Invite(p.get('invite')??'');}
 async function refresh(){try{S(await api('/api/platform'));}catch(e){if((e as any).status===401){S(null);try{const b=await api('/api/bootstrap');Auth(b.needsSetup?'setup':new URLSearchParams(location.search).has('invite')?'register':'login');}catch{E('本地服务不可用，请检查数据库后刷新。');}}else E((e as Error).message);}finally{L(false);}}
 useEffect(()=>{readRoute();refresh();window.addEventListener('popstate',readRoute);return()=>window.removeEventListener('popstate',readRoute);},[]);
 useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close();},[modal]);
 useEffect(()=>{
  const context=(document as any).modelContext;if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const register=(tool:any)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register({name:'list_demo_daos',title:'查看演示 DAO',description:'读取当前演示市场中的 DAO，不访问真实数据。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>{const s=await api('/api/platform');return s.catalog.map((d:any)=>({id:d.id,name:d.name}));}});
  register({name:'open_demo_dao',title:'打开演示 DAO',description:'进入所选 DAO 的演示详情，不创建或修改业务记录。',inputSchema:{type:'object',properties:{daoId:{type:'string'}},required:['daoId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:any)=>{const s=await api('/api/platform');if(typeof input?.daoId!=='string'||!s.catalog.some((d:any)=>d.id===input.daoId))throw Error('演示 DAO 不存在');navigate('center',input.daoId);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {opened:input.daoId,mode:'demo'};}});
  return()=>lifecycle.abort();
 },[]);
 function navigate(next:string,id='',part='center'){
  const p=new URLSearchParams();p.set('view',next);if(id){p.set('dao',id);p.set('section',part);}if(invite)p.set('invite',invite);
  history.pushState(null,'',sitePath('/?')+p);V(next);D(id);Section(part);E('');window.scrollTo(0,0);refresh();
 }
 async function logout(){resetDemo();location.href=sitePath('/');}
 async function signIn(e:React.FormEvent<HTMLFormElement>){e.preventDefault();B(true);E('');try{await api('/api/'+auth,{...Object.fromEntries(new FormData(e.currentTarget)),token:invite});if(auth==='register'){Invite('');history.replaceState(null,'',sitePath('/'));}await refresh();}catch(e){E((e as Error).message);}finally{B(false);}}
 async function accept(){B(true);E('');try{await api('/api/join',{token:invite});Invite('');history.replaceState(null,'',sitePath('/?view=center'));await refresh();N('加入申请已提交，请等待 DAO 管理员审批。');}catch(e){E((e as Error).message);}finally{B(false);}}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();B(true);E('');const values=Object.fromEntries(new FormData(e.currentTarget));try{
  if(modal==='profile')await api('/api/profile',values);
  else await api('/api/action',{daoId:data.memberships.find((m:any)=>m.status==='active'&&m.permissions.includes('manage'))?.daoId??'',op:'dao.create',input:values,requestId:crypto.randomUUID()});
  M(null);N('已保存');await refresh();
 }catch(e){E((e as Error).message);}finally{B(false);}}
 if(loading)return <main className="auth"><p>正在连接本地平台…</p></main>;
 if(!data)return <main className="auth"><form className="auth-card" onSubmit={signIn}><img src={sitePath("/logo.png")} width="64" height="64" alt="PonyDAO"/><p className="eyebrow">PONYDAO · 共建与共享</p><h1>{auth==='setup'?'创建你的账户':auth==='register'?'接受 DAO 邀请':'欢迎回来'}</h1><p className="muted">发现 DAO，与其他 OPC 一起创造价值。</p>{auth!=='login'&&<><label>姓名<input name="name" required maxLength={100}/></label><label>OPC 名称<input name="opc" required maxLength={100}/></label></>}<label>邮箱<input name="email" type="email" autoComplete="username" required/></label><label>密码（至少 10 位）<input name="password" type="password" minLength={10} maxLength={128} autoComplete={auth==='login'?'current-password':'new-password'} required/></label>{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={busy}>{busy?'正在处理…':auth==='setup'?'初始化平台':auth==='register'?'注册并申请加入':'登录'}</button>{auth!=='setup'&&<button type="button" className="link" onClick={()=>Auth(auth==='login'?'register':'login')}>{auth==='login'?'使用邀请链接注册':'已有账户，返回登录'}</button>}</form></main>;
 const user=data.user,catalog:any[]=data.catalog,bundles:any[]=data.bundles;
 const dao=catalog.find(d=>d.id===selected),bundle=bundles.find(b=>b.dao.id===selected);
 const admin=user.isPlatformAdmin;
 const allRecords=bundles.flatMap(b=>b.records.map((r:any)=>({...r,daoName:b.dao.name})));
 const ownAllocations=allRecords.filter(r=>r.kind==='allocation'&&r.status==='published'&&r.data.rows.some((s:any)=>s.userId===user.id));
 const withdrawals=allRecords.filter(r=>r.kind==='withdrawal'&&r.ownerId===user.id);
 const earned=ownAllocations.reduce((n,r)=>n+r.data.rows.find((s:any)=>s.userId===user.id).amount,0);
 const reserved=withdrawals.filter(r=>['pending','approved','paid'].includes(r.status)).reduce((n,r)=>n+r.data.amount,0);
 const notifications=allRecords.filter(r=>r.kind==='notification'&&r.ownerId===user.id&&r.status==='unread');
 const participating=allRecords.filter(r=>r.kind==='participation'&&r.ownerId===user.id);
 const myEvidence=allRecords.filter(r=>r.kind==='evidence'&&r.ownerId===user.id);
 const pendingMembers=bundles.flatMap(b=>b.member.permissions.includes('manage')?b.members.filter((m:any)=>m.status==='pending').map((m:any)=>({id:m.id,daoId:b.dao.id,daoName:b.dao.name,title:m.user.name+' 申请加入'})):[]);
 const pendingReviews=allRecords.filter(r=>{
  const b=bundles.find(b=>b.dao.id===r.daoId),manage=b.member.permissions.includes('manage'),finance=b.member.permissions.includes('finance');
  const asset=b.records.find((s:any)=>s.id===r.data.targetId),leader=asset?.data.leaderId===user.id;
  return (r.kind==='participation'&&r.status==='pending'&&(manage||leader))||(r.kind==='evidence'&&r.status==='pending'&&r.ownerId!==user.id&&(leader||b.member.permissions.includes('review')))||(r.kind==='allocation'&&r.status==='draft'&&finance&&r.ownerId!==user.id)||(r.kind==='withdrawal'&&['pending','approved'].includes(r.status)&&finance&&r.ownerId!==user.id)||(r.kind==='proposal'&&r.status==='voting'&&r.data.voters.includes(user.id)&&!b.records.some((v:any)=>v.kind==='vote'&&v.ownerId===user.id&&v.data.proposalId===r.id));
 });
 const mine=catalog.filter(d=>d.membership==='active');
 const filtered=catalog.filter(d=>(filter==='all'||d.membership==='active')&&(d.name+' '+d.mission).toLowerCase().includes(search.toLowerCase()));
 const canCreate=admin||data.memberships.some((m:any)=>m.status==='active'&&m.permissions.includes('manage'));
 const empty=(text:string)=><div className="empty"><Layers size={26}/><p>{text}</p></div>;
 function daoCards(items:any[]){return items.length?<div className="market-grid">{items.map(d=><article className="dao-card" key={d.id}><div className="row"><span className="dao-mark">{d.name.slice(0,2).toUpperCase()}</span><span className={'badge '+(d.membership==='active'?'approved':'')}>{d.membership?labels[d.membership]:admin?'平台管理':'待探索'}</span></div><h2>{d.name}</h2><p className="dao-mission">{d.mission}</p><div className="dao-counts"><span><strong>{d.memberCount}</strong>成员</span><span><strong>{d.productCount}</strong>产品</span><span><strong>{d.projectCount}</strong>项目</span></div><button className="primary" onClick={()=>navigate('center',d.id)}>进入 DAO <ArrowUpRight size={16}/></button></article>)}</div>:empty('没有匹配的 DAO，试试其他关键词。');}
 return <div className="shell platform"><a className="skip-link" href="#platform-main">跳到主要内容</a><aside><div className="brand"><img src={sitePath("/logo.png")} width="44" height="44" alt=""/><div><strong>PonyDAO</strong><small>DAO 协作与价值分配</small></div></div><nav aria-label="主导航">{navs.filter(n=>n[0]!=='profile').map(([key,label,Icon])=><button key={key} aria-current={view===key?'page':undefined} className={view===key?'selected':''} onClick={()=>navigate(key)}><Icon size={20}/><span>{label}</span></button>)}</nav><div className="aside-footer account-area"><button className={'account-card'+(view==='profile'?' selected':'')} aria-label="个人中心" aria-current={view==='profile'?'page':undefined} onClick={()=>navigate('profile')}><span className="avatar" aria-hidden="true">{user.name.slice(0,1)}</span><span className="account-copy"><strong>{user.name}</strong><small>{admin?'平台管理员 · 全平台权限':'OPC 成员 · 跨 DAO 协作'}</small><span className="account-link">个人中心</span></span><ChevronRight className="account-chevron" size={16} aria-hidden="true"/><span className="mobile-account-label">个人中心</span></button><button className="account-logout" onClick={logout}><LogOut size={16}/>重新体验</button></div></aside>
 <main className="main" id="platform-main"><header><span>PonyDAO <b>/</b>{navs.find(n=>n[0]===view)?.[1]??'DAO 中心'}</span></header>
 <div className="content"><div className="demo-bar"><div><strong>演示模式</strong><span>全部为虚拟数据 · 操作仅保存在当前浏览器 · 不产生真实交易</span></div><label>体验角色<select value={user.id} onChange={e=>{switchDemoUser(e.target.value);location.reload();}}>{(data.demoActors??demoUsers).map((u:any)=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><button onClick={()=>{if(confirm('重置当前浏览器中的演示操作？')){resetDemo();location.reload();}}}>重置演示</button></div>{notice&&<div className="notice" role="status"><span>{notice}</span><button aria-label="关闭通知" onClick={()=>N('')}>×</button></div>}{error&&!modal&&<p role="alert" className="error">{error}</p>}{invite&&<div className="notice"><span>检测到 DAO 邀请，使用当前账户申请加入。</span><button onClick={accept} disabled={busy}>接受邀请</button></div>}
 {selected&&view==='center'?(dao?bundle?<DaoDetail key={selected+section} initialDaoId={selected} initialView={section} onBack={()=>navigate('center')} onChanged={refresh}/>:<><button onClick={()=>navigate('center')}>← 返回 DAO 中心</button><section className="hero market-hero"><div><p>DAO 公开主页</p><h1>{dao.name}</h1><p>{dao.mission}</p></div><span className="badge">{dao.membership?labels[dao.membership]:'尚未加入'}</span></section><div className="notice"><span>{dao.membership==='pending'?'加入申请待审批，你仍可浏览平台中的其他 DAO。':'向 DAO 管理员获取邀请后即可申请加入。内部成果、财务和治理仅对获授权成员开放。'}</span></div><h2>公开产品与项目</h2>{dao.assets.length?<div className="two">{dao.assets.map((a:any)=><article key={a.id} className="card"><span className="badge">{a.kind==='product'?'产品':'项目'}</span><h2>{a.name}</h2><p>{a.description}</p><p>进度 {a.progress}%</p><progress max={100} value={a.progress}/></article>)}</div>:empty('该 DAO 尚未发布产品或项目。')}</>:<>{empty('这个 DAO 不存在或已经不可用。')}<button onClick={()=>navigate('center')}>返回 DAO 中心</button></>):<>
 {view==='center'&&<><section className="hero market-hero"><div><p className="eyebrow">DISCOVER · BUILD · SHARE</p><h1>发现值得一起建设的 DAO</h1><p>每一个 DAO，都是一群 OPC 共同创造价值的起点。</p><div className="market-stats"><span>{catalog.length} 个 DAO</span><span>{catalog.reduce((n,d)=>n+d.productCount,0)} 款产品</span><span>{catalog.reduce((n,d)=>n+d.projectCount,0)} 个项目</span></div></div>{canCreate&&<button onClick={()=>{E('');M('dao');}}><Plus size={17}/>创建 DAO</button>}</section><div className="market-toolbar"><div className="tabs"><button className={filter==='all'?'selected':''} aria-pressed={filter==='all'} onClick={()=>Filter('all')}>全部 DAO</button><button className={filter==='mine'?'selected':''} aria-pressed={filter==='mine'} onClick={()=>Filter('mine')}>我参与的（{mine.length}）</button></div><label className="search-field"><Search size={18}/><input aria-label="搜索 DAO" placeholder="搜索 DAO 名称或方向" value={search} onChange={e=>SearchText(e.target.value)}/></label></div>{daoCards(filtered)}</>}
 {view==='work'&&<><section className="heading"><div><p className="eyebrow">MY WORKBENCH</p><h1>工作台</h1><p className="muted">{user.name}，这里汇总你在各个 DAO 的协作与待办。</p></div><button className="primary" onClick={()=>navigate('center')}>探索 DAO</button></section><div className="metrics"><article><small>我加入的 DAO</small><strong>{mine.length}</strong></article><article><small>待处理事项</small><strong>{pendingMembers.length+pendingReviews.length}</strong></article><article><small>可提现收益</small><strong>{money(earned-reserved)}</strong></article></div><h2>待办与通知</h2>{!pendingMembers.length&&!pendingReviews.length&&!notifications.length?empty('暂无待办，去 DAO 中心发现新的协作机会。'):<>{pendingMembers.map(m=><article className="card row" key={m.id}><div><small>{m.daoName}</small><h3>{m.title}</h3></div><button onClick={()=>navigate('center',m.daoId,'work')}>前往审批</button></article>)}{pendingReviews.map(r=><article className="card row" key={r.id}><div><small>{r.daoName} · {labels[r.status]??r.status}</small><h3>{r.data.title??r.data.note??({participation:'参与申请',withdrawal:'提现审批',allocation:'分账审核'} as any)[r.kind]??'待处理事项'}</h3></div><button onClick={()=>navigate('center',r.daoId,['allocation','withdrawal'].includes(r.kind)?'ledger':r.kind==='proposal'?'center':'work')}>前往处理</button></article>)}{notifications.map(r=><article className="card row" key={r.id}><div><small>{r.daoName}</small><p>{r.data.message}</p></div><button onClick={()=>navigate('center',r.daoId,'work')}>查看通知</button></article>)}</>}<h2>我的参与与成果</h2>{[...participating,...myEvidence].length?[...participating,...myEvidence].map(r=><article key={r.id} className="card row"><div><small>{r.daoName} · {labels[r.status]??r.status}</small><h3>{r.data.title??allRecords.find(a=>a.id===r.data.targetId)?.data.name??'参与申请'}</h3></div><button onClick={()=>navigate('center',r.daoId,'work')}>查看协作</button></article>):empty('参与产品或项目后，进度和成果会汇总在这里。')}<h2>{admin?'可管理的 DAO':'我加入的 DAO'}</h2>{daoCards(admin?catalog:mine)}</>}
 {view==='ledger'&&<><section className="heading"><div><p className="eyebrow">MY REVENUE</p><h1>分账台</h1><p className="muted">跨 DAO 汇总个人收益；每笔分账与提现仍归属具体 DAO。</p></div></section><div className="metrics"><article><small>累计收益</small><strong>{money(earned)}</strong></article><article><small>已提现或冻结</small><strong>{money(reserved)}</strong></article><article><small>可提现余额</small><strong>{money(earned-reserved)}</strong></article></div><h2>按 DAO 查看收益与金库</h2>{bundles.length?bundles.map(b=>{const total=ownAllocations.filter(r=>r.daoId===b.dao.id).reduce((n,r)=>n+r.data.rows.find((s:any)=>s.userId===user.id).amount,0);const frozen=withdrawals.filter(r=>r.daoId===b.dao.id&&['pending','approved','paid'].includes(r.status)).reduce((n,r)=>n+r.data.amount,0);return <article className="card row" key={b.dao.id}><div><h3>{b.dao.name}</h3><p>我的收益 {money(total)} · 可提现 {money(total-frozen)}</p></div><button onClick={()=>navigate('center',b.dao.id,'ledger')}>{b.member.permissions.includes('finance')?'管理金库与分账':'查看收益与提现'}</button></article>}):empty('加入 DAO 后即可查看收益。')}<h2>收益来源</h2>{ownAllocations.length?ownAllocations.map(r=><article className="card row" key={r.id}><div><small>{r.daoName} · 规则版本 {r.data.ruleVersion}</small><h3>{r.data.note}</h3><p>来源：{allRecords.find(s=>s.id===r.data.sourceId)?.data.note}</p></div><strong className="amount">{money(r.data.rows.find((s:any)=>s.userId===user.id).amount)}</strong></article>):empty('暂无已发布收益。')}<h2>提现记录</h2>{withdrawals.length?withdrawals.map(r=><article className="card row" key={r.id}><div><small>{r.daoName} · {labels[r.status]}</small><h3>{money(r.data.amount)}</h3><p>{r.data.account}</p></div><button onClick={()=>navigate('center',r.daoId,'ledger')}>查看详情</button></article>):empty('暂无提现记录。')}</>}
 {view==='profile'&&<><section className="heading"><div><p className="eyebrow">PROFILE</p><h1>个人中心</h1><p className="muted">一个平台账户，参与多个 DAO。</p></div></section><article className="card"><span className="avatar large">{user.name.slice(0,1)}</span><h2>{user.name}</h2><p>{user.email}</p><p>{user.opc}</p><p>{admin?'平台管理员：拥有全部 DAO 的管理、财务和成果确认权限。':'各 DAO 的角色和管理权限独立授予。'}</p>{admin&&<p className="muted">平台权限不改变一人一票、余额校验与双人审核。测试分账发布、成果确认或自己的提现时，需另一成员账户参与。</p>}<div className="actions"><button onClick={()=>{E('');M('profile');}}>编辑个人资料</button><button onClick={logout}>重新体验</button></div></article><h2>我的 DAO 身份</h2>{data.memberships.length?data.memberships.map((m:any)=><article className="card row" key={m.id}><div><h3>{m.dao.name}</h3><p>{m.roles.map((r:string)=>labels[r]+' OPC').join(' / ')} · {labels[m.status]}</p><small>权限：{admin?'平台全部权限':m.permissions.map((p:string)=>labels[p]).join('、')||'普通成员'}</small></div><button onClick={()=>navigate('center',m.daoId)}>进入 DAO</button></article>):empty('尚未加入 DAO，可以先浏览 DAO 中心。')}</>}
 </>}</div></main><dialog ref={dialog} aria-labelledby="platform-modal" onCancel={()=>M(null)}>{modal&&<form key={modal} onSubmit={save}><div className="row"><h2 id="platform-modal">{modal==='dao'?'创建 DAO':'编辑个人资料'}</h2><button type="button" aria-label="关闭" onClick={()=>M(null)}>×</button></div><label>{modal==='dao'?'DAO 名称':'姓名'} *<input name="name" required maxLength={100} defaultValue={modal==='profile'?user.name:''}/></label>{modal==='dao'?<label>使命与说明 *<textarea name="mission" required maxLength={3000} rows={4}/></label>:<label>OPC 名称 *<input name="opc" required maxLength={100} defaultValue={user.opc}/></label>}{error&&<p className="error" role="alert">{error}</p>}<div className="actions"><button className="primary" disabled={busy}>{busy?'正在保存…':'确认保存'}</button><button type="button" onClick={()=>M(null)} disabled={busy}>取消</button></div></form>}</dialog></div>;
}
